CREATE TABLE person_data (
    hospcode VARCHAR(5) NOT NULL,
    cid VARCHAR(13) NOT NULL,
    pid INT,
    hid VARCHAR(10),
    prename VARCHAR(10),
    name VARCHAR(100),
    lname VARCHAR(100),
    hn VARCHAR(20),
    sex CHAR(1),
    birth DATE,
    mstatus CHAR(1),
    occupation_old VARCHAR(10),
    occupation_new VARCHAR(10),
    race VARCHAR(10),
    nation VARCHAR(10),
    religion VARCHAR(10),
    education VARCHAR(10),
    fstatus VARCHAR(1),
    father VARCHAR(13),
    mother VARCHAR(13),
    couple VARCHAR(13),
    vstatus VARCHAR(1),
    movein DATE,
    discharge VARCHAR(1),
    ddischarge DATE,
    abogroup VARCHAR(2),
    rhgroup VARCHAR(2),
    labor VARCHAR(1),
    passport VARCHAR(20),
    typearea VARCHAR(1),
    d_update DATETIME,
    telephone VARCHAR(20),
    mobile VARCHAR(20),
    PRIMARY KEY (cid,hospcode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
